<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\Application.Client\Application.Client.csproj" />
    <ProjectReference Include="..\..\src\Application.Server\Application.Server.csproj" />
    <ProjectReference Include="..\..\src\Domain\Domain.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.EFCore.Server.Identity\Infrastructure.EFCore.Server.Identity.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.Server.Identity\Infrastructure.Server.Identity.csproj" />
  </ItemGroup>

</Project>
