name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
    timeout-minutes: 30
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CONDITION }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_SUBMODULES }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_FETCH_TAGS: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_SUBMODULES: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
  APPLICATIONBUILDERHELPERSBUILD:
    name: Build - application_builder_helpers (ApplicationBuilderHelpersBuild)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUN_SCRIPT }} PipelineRunEntry --args "run=build;idsToRun=ApplicationBuilderHelpersBuild"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build___application_builder_helpers___APPLICATIONBUILDERHELPERSBUILD
        path: ./.nuke/temp/artifacts-upload/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  APPLICATIONBUILDERHELPERSPUBLISH:
    name: Publish - application_builder_helpers (ApplicationBuilderHelpersPublish)
    runs-on: ${{ fromJson(needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUNS_ON) }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_FETCH_DEPTH }}
        fetch-tags: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_FETCH_TAGS }}
        submodules: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CHECKOUT_SUBMODULES }}
        persist-credentials: true
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: build___application_builder_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/temp/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineRunEntry
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUN_SCRIPT }} PipelineRunEntry --args "run=publish;idsToRun=ApplicationBuilderHelpersPublish"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: publish___application_builder_helpers___APPLICATIONBUILDERHELPERSPUBLISH
        path: ./.nuke/temp/artifacts-upload/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    - APPLICATIONBUILDERHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CONDITION == 'true' && needs.APPLICATIONBUILDERHELPERSBUILD.result == 'success'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on:
      labels: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
        submodules: recursive
        persist-credentials: true
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts-download
        pattern: publish___*
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
    needs:
    - PRE_SETUP
    - APPLICATIONBUILDERHELPERSBUILD
    - APPLICATIONBUILDERHELPERSPUBLISH
    if: success() || failure() || always()
    timeout-minutes: 30
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_APPLICATIONBUILDERHELPERSBUILD: ${{ needs.APPLICATIONBUILDERHELPERSBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_APPLICATIONBUILDERHELPERSPUBLISH: ${{ needs.APPLICATIONBUILDERHELPERSPUBLISH.result }}
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
