name: Nuke CICD Pipeline
on:
  push:
    branches:
    - prerelease
    - master
    tags:
    - bump-*
  pull_request:
    branches:
    - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  PRE_SETUP:
    name: Pre Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - id: NUKE_RUN
      name: Run Nuke PipelinePreSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePreSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      NUKE_PRE_SETUP: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP }}
      NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_TEST_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_BUILD_MATRIX }}
      NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_OUTPUT_PUBLISH_MATRIX }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CONDITION }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUNS_ON }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUN_SCRIPT }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CONDITION: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CONDITION }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUNS_ON: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUNS_ON }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUN_SCRIPT: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUN_SCRIPT }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_RESTORE_KEY }}
      NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY: ${{ steps.NUKE_RUN.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
  APPLICATIONBUILDERHELPERSBUILD:
    name: Build - application_builder_helpers (ApplicationBuilderHelpersBuild)
    runs-on: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUNS_ON }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelineBuild
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_RUN_SCRIPT }} PipelineBuild --args "ApplicationBuilderHelpersBuild"
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: application_builder_helpers___APPLICATIONBUILDERHELPERSBUILD
        path: ./.nuke/output/*
        if-no-files-found: error
        retention-days: 1
    needs:
    - PRE_SETUP
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSBUILD_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  APPLICATIONBUILDERHELPERSPUBLISH:
    name: Publish - application_builder_helpers (ApplicationBuilderHelpersPublish)
    runs-on: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUNS_ON }}
    steps:
    - uses: actions/checkout@v4
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
        pattern: application_builder_helpers___*
    - name: Cache Run
      uses: actions/cache@v4
      with:
        path: ./.nuke/cache
        key: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_KEY }}
        restore-keys: |-
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_RESTORE_KEY }}
          ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CACHE_MAIN_RESTORE_KEY }}
    - id: NUKE_RUN
      name: Run Nuke PipelinePublish
      run: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_RUN_SCRIPT }} PipelinePublish --args "ApplicationBuilderHelpersPublish"
    needs:
    - PRE_SETUP
    - APPLICATIONBUILDERHELPERSBUILD
    if: "! failure() && ! cancelled() && needs.PRE_SETUP.outputs.NUKE_PRE_SETUP_APPLICATIONBUILDERHELPERSPUBLISH_CONDITION == 'true'"
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
  POST_SETUP:
    name: Post Setup
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./.nuke/temp/artifacts
    - name: Run Nuke PipelinePostSetup
      run: chmod +x ./build.sh && ./build.sh PipelinePostSetup
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    needs:
    - PRE_SETUP
    - APPLICATIONBUILDERHELPERSBUILD
    - APPLICATIONBUILDERHELPERSPUBLISH
    if: success() || failure() || always()
    env:
      NUKE_PRE_SETUP: ${{ needs.PRE_SETUP.outputs.NUKE_PRE_SETUP }}
      NUKE_RUN_RESULT_GITHUB_APPLICATIONBUILDERHELPERSBUILD: ${{ needs.APPLICATIONBUILDERHELPERSBUILD.result }}
      NUKE_RUN_RESULT_GITHUB_APPLICATIONBUILDERHELPERSPUBLISH: ${{ needs.APPLICATIONBUILDERHELPERSPUBLISH.result }}
env:
  NUKE_NUGET_AUTH_TOKEN: ${{ secrets.NUGET_AUTH_TOKEN }}
  NUKE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
