<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <xUnitParallelizeTestCollections>false</xUnitParallelizeTestCollections>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Application\Application.csproj" />
    <ProjectReference Include="..\..\src\Application.Server\Application.Server.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.EFCore\Infrastructure.EFCore.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.EFCore.Server.Identity\Infrastructure.EFCore.Server.Identity.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.EFCore.LocalStore\Infrastructure.EFCore.LocalStore.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.EFCore.Sqlite\Infrastructure.EFCore.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Infrastructure.Server.Identity\Infrastructure.Server.Identity.csproj" />
  </ItemGroup>

</Project>
